// <auto-generated />
using System;
using AMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMS.Infrastructure.Migrations
{
    [DbContext(typeof(AmsDbContext))]
    partial class AmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("alarms")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMS.Domain.Alarms.ActiveAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AckComment")
                        .HasColumnType("text")
                        .HasColumnName("ack_comment");

                    b.Property<DateTimeOffset?>("AckTime")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("ack_time");

                    b.Property<Guid?>("AckedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("acked_by");

                    b.Property<bool>("Acknowledged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acknowledged");

                    b.Property<DateTimeOffset>("ActiveTime")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("active_time");

                    b.Property<Guid?>("AlarmTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("alarm_tag_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("alarms.alarm_category")
                        .HasColumnName("category");

                    b.Property<bool>("ConditionActive")
                        .HasColumnType("boolean")
                        .HasColumnName("condition_active");

                    b.Property<string>("ConditionName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("condition_name");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomAttributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_attributes");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("event_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("alarms.event_type")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsOutOfService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_out_of_service");

                    b.Property<bool>("IsRootCause")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_root_cause");

                    b.Property<bool>("IsShelved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_shelved");

                    b.Property<bool>("IsSuppressed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_suppressed");

                    b.Property<long?>("KafkaOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("kafka_offset");

                    b.Property<int?>("KafkaPartition")
                        .HasColumnType("integer")
                        .HasColumnName("kafka_partition");

                    b.Property<string>("KafkaTopic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("kafka_topic");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("OpcAttributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("opc_attributes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("alarms.alarm_priority")
                        .HasColumnName("priority");

                    b.Property<string>("ProcessUnit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("process_unit");

                    b.Property<double?>("ProcessValue")
                        .HasColumnType("double precision")
                        .HasColumnName("process_value");

                    b.Property<int>("Quality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(192)
                        .HasColumnName("quality");

                    b.Property<Guid?>("RootCauseAlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_cause_alarm_id");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<DateTimeOffset>("ServerReceivedAt")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("server_received_at");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("ShelveComment")
                        .HasColumnType("text")
                        .HasColumnName("shelve_comment");

                    b.Property<DateTimeOffset?>("ShelveUntil")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("shelve_until");

                    b.Property<DateTimeOffset?>("ShelvedAt")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("shelved_at");

                    b.Property<Guid?>("ShelvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("shelved_by");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("alarms.alarm_state")
                        .HasColumnName("alarm_state");

                    b.Property<string>("SubConditionName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sub_condition_name");

                    b.Property<DateTimeOffset?>("SuppressedAt")
                        .HasColumnType("timestamptz(3)")
                        .HasColumnName("suppressed_at");

                    b.Property<Guid?>("SuppressedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("suppressed_by");

                    b.Property<string>("SuppressionReason")
                        .HasColumnType("text")
                        .HasColumnName("suppression_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_active_alarms");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_active_alarms_correlation")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("EventTime")
                        .IsDescending()
                        .HasDatabaseName("idx_active_alarms_event_time");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_active_alarms_priority");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("idx_active_alarms_server");

                    b.HasIndex("State")
                        .HasDatabaseName("idx_active_alarms_state");

                    b.ToTable("active_alarms", "alarms");
                });
#pragma warning restore 612, 618
        }
    }
}
