#!/usr/bin/env python3
"""Generate the two pgAdmin-runnable HDPE seed scripts in database/seeds/:

  seed_01_hdpe_plant_hierarchy.sql  -> run against traverse_assets
        database/scripts/48_hdpe_plant_hierarchy.sql minus the psql-only `\\c`
        (pgAdmin's query tool cannot execute psql meta-commands).

  seed_02_hdpe_loop_registry.sql    -> run against traverse_cplm
        All loops from scripts/fixtures/hdpe-all-loops.csv as cpm.loop_registry +
        cpm.loop_tag_map upserts, byte-compatible with what cplm-api's activate
        endpoint writes (same JSONB shapes, same ON CONFLICT merge semantics).

Both are idempotent - safe to re-run. Regenerate after editing the fixture:
    python scripts/make-hdpe-seed-sql.py
"""
import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
FIXTURE = REPO / "scripts" / "fixtures" / "hdpe-all-loops.csv"
SCRIPT_48 = REPO / "database" / "scripts" / "48_hdpe_plant_hierarchy.sql"
OUT_DIR = REPO / "database" / "seeds"
OUT_HIER = OUT_DIR / "seed_01_hdpe_plant_hierarchy.sql"
OUT_LOOPS = OUT_DIR / "seed_02_hdpe_loop_registry.sql"

HIER_HEADER = """\
-- =============================================================================
-- seed_01_hdpe_plant_hierarchy.sql  —  RUN AGAINST DATABASE: traverse_assets
--
-- pgAdmin: open the Query Tool ON traverse_assets and execute this file.
-- Seeds the HDPE plant tree (1 site, 7 areas + Unassigned, 25 units) and the
-- Instrumental-Pro alias rows. Identical to database/scripts/48 minus the
-- psql-only \\c meta-command. Idempotent (ON CONFLICT DO NOTHING throughout;
-- assets.assets is guarded by the unique index on contextual_path).
--
-- Run this BEFORE seed_02 — loop activation/UI location validation expects
-- these site/area/unit nodes to exist.
-- Generated by scripts/make-hdpe-seed-sql.py — edit the generator, not this file.
-- =============================================================================
"""

LOOPS_HEADER = """\
-- =============================================================================
-- seed_02_hdpe_loop_registry.sql  —  RUN AGAINST DATABASE: traverse_cplm
--
-- pgAdmin: open the Query Tool ON traverse_cplm and execute this file.
-- Seeds all {count} HDPE control loops (source: the plant's OT loop export via
-- scripts/fixtures/hdpe-all-loops.csv): one cpm.loop_registry row per loop plus
-- four cpm.loop_tag_map rows (PV/SP/OP/MODE with Yokogawa SV/MV source tags).
-- JSONB shapes and ON CONFLICT merge semantics mirror cplm-api's activate
-- endpoint exactly, so seeded rows are indistinguishable from API-onboarded
-- ones for the UI, readiness, and the OT ingestion joiner. Idempotent.
--
-- What SQL seeding does NOT do (API-only side effects):
--   * signal-asset projection into traverse_assets (UNS Measurement/Device
--     nodes + transport overrides for HMI binding of the loop signals)
--   * the Kafka evidence broadcast (traverse.cpa.ams.metadata.updates) that
--     hands Flink the loop engineering ranges / step-test evidence
-- Neither blocks ingestion, trends, or the registry UI. To backfill both, run
-- once after seeding (idempotent upsert re-projects + re-publishes):
--     .\\scripts\\import-cpm-loops.ps1 -CsvPath scripts\\fixtures\\hdpe-all-loops.csv
-- or POST /api/v1/cpm/loops/{{loopId}}/republish-evidence per loop.
--
-- Requires seed_01 applied to traverse_assets first (locations must exist).
-- Generated by scripts/make-hdpe-seed-sql.py — edit the generator, not this file.
-- =============================================================================

BEGIN;
"""

MONITORING_JSON = ('{"enabled": true, "cplmPipeline": "cplm-three-stage-system", '
                   '"evidence": {"stepTestApproved": false, "peerLinksConfigured": false}}')

ROLES = ("PV", "SP", "OP", "MODE")
SOURCE_COL = {"PV": "pv_ot_tag", "SP": "sp_ot_tag", "OP": "op_ot_tag", "MODE": "mode_ot_tag"}


def q(value: str) -> str:
    """SQL single-quote a literal."""
    return "'" + value.replace("'", "''") + "'"


def main():
    # ── seed 1: hierarchy (script 48 minus psql meta-commands) ───────────────
    lines = SCRIPT_48.read_text(encoding="utf-8").splitlines()
    body = "\n".join(l for l in lines if not l.strip().startswith("\\c"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_HIER.write_text(HIER_HEADER + body + "\n", encoding="utf-8")

    # ── seed 2: loop registry from the fixture ───────────────────────────────
    with FIXTURE.open(newline="", encoding="utf-8-sig") as f:
        rows = [r for r in csv.DictReader(f) if r["loop_id"].strip()]

    out = [LOOPS_HEADER.format(count=len(rows))]
    for r in rows:
        loop = r["loop_id"].strip()
        site, area, unit = r["site"].strip(), r["area"].strip(), r["unit"].strip()
        prefix = "/".join(p for p in (site, area, unit) if p).lower()
        paths = {role: f"{prefix}/{loop.lower()}.{role.lower()}" for role in ROLES}
        tags_json = "{" + ", ".join(f'"{role.lower()}": "{paths[role]}"' for role in ROLES) + "}"
        engineering_json = f'{{"opMin": {float(r["op_min"] or 0):g}, "opMax": {float(r["op_max"] or 100):g}}}'

        out.append(f"""\
-- ── {loop} ──
INSERT INTO cpm.loop_registry
    (loop_id, asset_id, display_name, site, area, unit, loop_type, criticality,
     is_active, monitoring, tags, engineering, threshold_profile_id, updated_at)
VALUES
    ({q(loop)}, NULL, {q(r['display_name'].strip())}, {q(site)}, {q(area)}, {q(unit)},
     {q(r['loop_type'].strip().upper())}, {q(r['criticality'].strip().lower())},
     TRUE, {q(MONITORING_JSON)}::jsonb, {q(tags_json)}::jsonb, {q(engineering_json)}::jsonb,
     NULL, NOW())
ON CONFLICT (loop_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    site = EXCLUDED.site, area = EXCLUDED.area, unit = EXCLUDED.unit,
    loop_type = EXCLUDED.loop_type, criticality = EXCLUDED.criticality,
    is_active = TRUE, tags = EXCLUDED.tags,
    monitoring = cpm.loop_registry.monitoring || EXCLUDED.monitoring,
    engineering = EXCLUDED.engineering,
    updated_at = NOW();
""")
        # Replace the role mapping wholesale, exactly like the activate endpoint —
        # an upsert alone would leave stale rows behind when a loop's placement moved.
        out.append(f"DELETE FROM cpm.loop_tag_map WHERE loop_id = {q(loop)};\n")
        for role in ROLES:
            source_tag = r[SOURCE_COL[role]].strip()
            out.append(
                "INSERT INTO cpm.loop_tag_map (loop_id, signal_role, uns_path, source_system, source_tag)\n"
                f"VALUES ({q(loop)}, {q(role)}, {q(paths[role])}, 'ot-gateway', {q(source_tag)});\n")
        out.append("")

    out.append("""\
COMMIT;

DO $$ BEGIN RAISE NOTICE 'HDPE loop registry seeded ({count} loops x 4 signal roles)'; END $$;
""".format(count=len(rows)))
    OUT_LOOPS.write_text("\n".join(out), encoding="utf-8")

    print(f"wrote {OUT_HIER}")
    print(f"wrote {OUT_LOOPS}  ({len(rows)} loops, {len(rows) * 4} tag-map rows)")


if __name__ == "__main__":
    main()
