<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AMS.HistorianBff</RootNamespace>
    <AssemblyName>historian-bff</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Redis -->
    <PackageReference Include="StackExchange.Redis" Version="2.7.33" />
    <!-- Minimal API health checks -->
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.0" />
  </ItemGroup>

</Project>
