import type { SymbolCategory, SymbolDefinition } from './types';

const obc = (sym: Omit<SymbolDefinition, 'isOpenBridge'>): SymbolDefinition => ({
  ...sym,
  isOpenBridge: true,
});

const sym = (
  category: string,
  catId: string,
  id: string,
  label: string,
  icon: string,
  defaultSize: { width: number; height: number },
  bindingSlots: string[] = [],
  extra?: Partial<SymbolDefinition>
): SymbolDefinition =>
  obc({
    type: `obc.ob.${category}.${id}`,
    label,
    icon,
    category: catId,
    defaultSize,
    bindingSlots,
    description: extra?.description ?? `OpenBridge ${label}`,
    ...extra,
  });

/** OpenBridge Storybook catalog — UI, Bars/Graphs, Instruments, Indicators, AR, Building Blocks */
export const OPENBRIDGE_CATALOG_LIBRARY: SymbolCategory[] = [
  {
    id: 'obc-ui',
    name: 'UI Components',
    icon: '▣',
    symbols: [
      sym('ui', 'obc-ui', 'button', 'Button', 'Btn', { width: 120, height: 44 }, ['command']),
      sym('ui', 'obc-ui', 'icon-button', 'Icon Button', 'Ico', { width: 44, height: 44 }),
      sym('ui', 'obc-ui', 'check-button', 'Check Button', 'Chk', { width: 100, height: 36 }, ['state']),
      sym('ui', 'obc-ui', 'command-button', 'Command Button', 'Cmd', { width: 120, height: 44 }, ['command']),
      sym('ui', 'obc-ui', 'rich-button', 'Rich Button', 'Rch', { width: 140, height: 52 }),
      sym('ui', 'obc-ui', 'toggle-switch', 'Toggle Switch', 'Tgl', { width: 60, height: 32 }, ['state']),
      sym('ui', 'obc-ui', 'start-stop-switch', 'Start/Stop Switch', 'SS', { width: 80, height: 40 }, ['state']),
      sym('ui', 'obc-ui', 'slider', 'Slider', 'Sld', { width: 40, height: 150 }, ['value']),
      sym('ui', 'obc-ui', 'slider-double', 'Double Slider', '2S', { width: 40, height: 150 }, ['value', 'setpoint']),
      sym('ui', 'obc-ui', 'number-input', 'Number Input', 'Num', { width: 120, height: 44 }, ['value']),
      sym('ui', 'obc-ui', 'text-input', 'Text Input', 'Txt', { width: 160, height: 44 }, ['text']),
      sym('ui', 'obc-ui', 'textarea', 'Text Area', 'Ta', { width: 200, height: 80 }, ['text']),
      sym('ui', 'obc-ui', 'dropdown-button', 'Dropdown', 'Dd', { width: 140, height: 44 }),
      sym('ui', 'obc-ui', 'split-button', 'Split Button', 'Sp', { width: 140, height: 44 }),
      sym('ui', 'obc-ui', 'menu-button', 'Menu Button', 'Men', { width: 120, height: 44 }),
      sym('ui', 'obc-ui', 'card', 'Card', 'Crd', { width: 240, height: 160 }),
      sym('ui', 'obc-ui', 'elevated-card', 'Elevated Card', 'Elv', { width: 240, height: 160 }),
      sym('ui', 'obc-ui', 'tabbed-card', 'Tabbed Card', 'Tab', { width: 280, height: 200 }),
      sym('ui', 'obc-ui', 'accordion-card', 'Accordion Card', 'Acc', { width: 280, height: 120 }),
      sym('ui', 'obc-ui', 'divider', 'Divider', '─', { width: 200, height: 2 }),
      sym('ui', 'obc-ui', 'navigation-item', 'Nav Item', 'Nav', { width: 160, height: 44 }),
      sym('ui', 'obc-ui', 'breadcrumb', 'Breadcrumb', 'Bc', { width: 320, height: 32 }),
      sym('ui', 'obc-ui', 'table', 'Table', 'Tbl', { width: 400, height: 200 }),
      sym('ui', 'obc-ui', 'pagination', 'Pagination', 'Pg', { width: 240, height: 40 }),
      sym('ui', 'obc-ui', 'modal-window', 'Modal Window', 'Mod', { width: 360, height: 240 }),
      sym('ui', 'obc-ui', 'tooltip', 'Tooltip', 'Tip', { width: 120, height: 32 }),
      sym('ui', 'obc-ui', 'alert-button', 'Alert Button', 'Alr', { width: 100, height: 44 }, ['alarms']),
      sym('ui', 'obc-ui', 'form-container', 'Form Container', 'Frm', { width: 280, height: 200 }),
      sym('ui', 'obc-ui', 'radio', 'Radio', 'Rad', { width: 120, height: 32 }, ['state']),
      sym('ui', 'obc-ui', 'checkbox', 'Checkbox', 'Cb', { width: 120, height: 32 }, ['state']),
      sym('ui', 'obc-ui', 'tag', 'Tag', 'Tag', { width: 80, height: 28 }, ['text']),
      sym('ui', 'obc-ui', 'filter-chip', 'Filter Chip', 'Flt', { width: 100, height: 32 }),
      sym('ui', 'obc-ui', 'progress-button', 'Progress Button', 'Prg', { width: 120, height: 44 }),
      sym('ui', 'obc-ui', 'clock', 'Clock', 'Clk', { width: 100, height: 32 }),
      sym('ui', 'obc-ui', 'badge', 'Badge', 'Bdg', { width: 80, height: 28 }, ['text']),
      sym('ui', 'obc-ui', 'notification-button', 'Notification', 'Ntf', { width: 44, height: 44 }),
      sym('ui', 'obc-ui', 'keyboard-numeric', 'Numeric Keyboard', 'Kb', { width: 240, height: 280 }),
      sym('ui', 'obc-ui', 'stepper-box', 'Stepper Box', 'Stp', { width: 200, height: 48 }),
      sym('ui', 'obc-ui', 'title-container', 'Title Container', 'Ttl', { width: 240, height: 48 }),
      sym('ui', 'obc-ui', 'event-list', 'Event List', 'Evt', { width: 320, height: 200 }),
      sym('ui', 'obc-ui', 'advice-button', 'Advice Button', 'Adv', { width: 120, height: 44 }),
      sym('ui', 'obc-ui', 'system-button', 'System Button', 'Sys', { width: 120, height: 44 }),
      sym('ui', 'obc-ui', 'vendor-button', 'Vendor Button', 'Vnd', { width: 120, height: 44 }),
    ],
  },
  {
    id: 'obc-bars-graphs',
    name: 'Bars and Graphs',
    icon: '📊',
    symbols: [
      sym('graph', 'obc-bars-graphs', 'bar-vertical', 'Bar Vertical', '▮', { width: 80, height: 200 }, ['value'], { hasAlarmLimits: true }),
      sym('graph', 'obc-bars-graphs', 'bar-horizontal', 'Bar Horizontal', '▬', { width: 200, height: 80 }, ['value'], { hasAlarmLimits: true }),
      sym('graph', 'obc-bars-graphs', 'progress-bar', 'Progress Bar', '═', { width: 200, height: 24 }, ['value']),
      sym('graph', 'obc-bars-graphs', 'circular-progress', 'Circular Progress', '◔', { width: 80, height: 80 }, ['value']),
      sym('graph', 'obc-bars-graphs', 'graph-mini', 'Mini Graph', '⌇', { width: 200, height: 80 }, ['value']),
      sym('graph', 'obc-bars-graphs', 'gauge-trend', 'Gauge Trend', '📈', { width: 280, height: 180 }, ['value'], { hasAlarmLimits: true }),
    ],
  },
  {
    id: 'obc-instruments',
    name: 'Instruments',
    icon: '🧭',
    symbols: [
      sym('inst', 'obc-instruments', 'gauge-radial', 'Gauge Radial', '◎', { width: 160, height: 160 }, ['value'], { hasAlarmLimits: true }),
      sym('inst', 'obc-instruments', 'gauge-vertical', 'Gauge Vertical', '▮', { width: 80, height: 200 }, ['value'], { hasAlarmLimits: true }),
      sym('inst', 'obc-instruments', 'gauge-horizontal', 'Gauge Horizontal', '▬', { width: 200, height: 80 }, ['value'], { hasAlarmLimits: true }),
      sym('inst', 'obc-instruments', 'instrument-radial', 'Instrument Radial', '◉', { width: 160, height: 160 }, ['value'], { hasAlarmLimits: true }),
      sym('inst', 'obc-instruments', 'thruster', 'Thruster', 'Thr', { width: 80, height: 200 }, ['value']),
      sym('inst', 'obc-instruments', 'azimuth-thruster', 'Azimuth Thruster', 'Az', { width: 120, height: 120 }, ['value']),
      sym('inst', 'obc-instruments', 'main-engine', 'Main Engine', 'ME', { width: 80, height: 200 }, ['value', 'status']),
      sym('inst', 'obc-instruments', 'compass', 'Compass', 'Cps', { width: 160, height: 160 }, ['value']),
      sym('inst', 'obc-instruments', 'compass-flat', 'Compass Flat', 'Cf', { width: 200, height: 80 }, ['value']),
      sym('inst', 'obc-instruments', 'compass-indicator', 'Compass Indicator', 'Ci', { width: 120, height: 120 }, ['value']),
      sym('inst', 'obc-instruments', 'speed-gauge', 'Speed Gauge', 'Spd', { width: 160, height: 160 }, ['value']),
      sym('inst', 'obc-instruments', 'speed-indicator', 'Speed Indicator', 'Si', { width: 120, height: 48 }, ['value']),
      sym('inst', 'obc-instruments', 'speed-arrows', 'Speed Arrows', 'Sa', { width: 120, height: 48 }, ['value']),
      sym('inst', 'obc-instruments', 'rudder', 'Rudder', 'Rud', { width: 120, height: 80 }, ['value']),
      sym('inst', 'obc-instruments', 'rot-indicator', 'ROT Indicator', 'Rot', { width: 120, height: 80 }, ['value']),
      sym('inst', 'obc-instruments', 'heading', 'Heading', 'Hdg', { width: 120, height: 48 }, ['value']),
      sym('inst', 'obc-instruments', 'wind', 'Wind', 'Wnd', { width: 120, height: 120 }, ['value']),
      sym('inst', 'obc-instruments', 'wind-indicator', 'Wind Indicator', 'Wi', { width: 80, height: 80 }, ['value']),
      sym('inst', 'obc-instruments', 'pitch', 'Pitch', 'Pit', { width: 120, height: 80 }, ['value']),
      sym('inst', 'obc-instruments', 'roll', 'Roll', 'Rol', { width: 120, height: 80 }, ['value']),
      sym('inst', 'obc-instruments', 'pitch-roll', 'Pitch & Roll', 'PR', { width: 160, height: 120 }, ['value']),
      sym('inst', 'obc-instruments', 'depth-actual', 'Depth Actual', 'Dep', { width: 80, height: 200 }, ['value']),
      sym('inst', 'obc-instruments', 'heave', 'Heave', 'Hv', { width: 80, height: 120 }, ['value']),
      sym('inst', 'obc-instruments', 'rate-of-turn', 'Rate of Turn', 'RoT', { width: 120, height: 80 }, ['value']),
      sym('inst', 'obc-instruments', 'instrument-field', 'Instrument Field', 'Fld', { width: 120, height: 48 }, ['value']),
      sym('inst', 'obc-instruments', 'bearing-indicator', 'Bearing Indicator', 'Brg', { width: 120, height: 48 }, ['value']),
      sym('inst', 'obc-instruments', 'watch', 'Watch', 'Wch', { width: 200, height: 200 }, ['value']),
      sym('inst', 'obc-instruments', 'watch-flat', 'Watch Flat', 'Wf', { width: 280, height: 120 }, ['value']),
      sym('inst', 'obc-instruments', 'velocity-projection-plot', 'Velocity Plot', 'Vel', { width: 200, height: 200 }, ['value']),
    ],
  },
  {
    id: 'obc-indicators',
    name: 'Indicators',
    icon: '●',
    symbols: [
      sym('ind', 'obc-indicators', 'status-indicator', 'Status Indicator', 'St', { width: 120, height: 32 }, ['status']),
      sym('ind', 'obc-indicators', 'battery-icon', 'Battery Icon', 'Bat', { width: 48, height: 24 }, ['value']),
      sym('ind', 'obc-indicators', 'progress-dots', 'Progress Dots', '···', { width: 80, height: 16 }),
      sym('ind', 'obc-indicators', 'alert-icon', 'Alert Icon', '!', { width: 40, height: 40 }, ['state']),
      sym('ind', 'obc-indicators', 'alert-frame', 'Alert Frame', 'Fr', { width: 120, height: 80 }, ['state']),
      sym('ind', 'obc-indicators', 'badge-command', 'Badge Command', 'Bc', { width: 48, height: 48 }),
    ],
  },
  {
    id: 'obc-ar',
    name: 'AR',
    icon: '🗺',
    symbols: [
      sym('ar', 'obc-ar', 'poi-vessel', 'POI Vessel', 'Vsl', { width: 48, height: 48 }, ['asset']),
      sym('ar', 'obc-ar', 'poi-aton', 'POI ATON', 'Ato', { width: 48, height: 48 }),
      sym('ar', 'obc-ar', 'poi-data', 'POI Data', 'Dat', { width: 48, height: 48 }, ['value']),
      sym('ar', 'obc-ar', 'poi-card', 'POI Card', 'Pc', { width: 240, height: 120 }),
      sym('ar', 'obc-ar', 'poi-card-header', 'POI Card Header', 'Ph', { width: 240, height: 48 }),
      sym('ar', 'obc-ar', 'poi-controller', 'POI Controller', 'Ctl', { width: 200, height: 48 }),
      sym('ar', 'obc-ar', 'poi-group', 'POI Group', 'Grp', { width: 200, height: 120 }),
      sym('ar', 'obc-ar', 'poi-layer', 'POI Layer', 'Lyr', { width: 200, height: 48 }),
      sym('ar', 'obc-ar', 'poi-layer-stack', 'POI Layer Stack', 'Ls', { width: 200, height: 120 }),
      sym('ar', 'obc-ar', 'poi-button-vessel', 'POI Button Vessel', 'Bv', { width: 48, height: 48 }),
      sym('ar', 'obc-ar', 'poi-button-aton', 'POI Button ATON', 'Ba', { width: 48, height: 48 }),
      sym('ar', 'obc-ar', 'poi-button-data', 'POI Button Data', 'Bd', { width: 48, height: 48 }),
      sym('ar', 'obc-ar', 'poi-object-vessel', 'POI Object Vessel', 'Ov', { width: 48, height: 48 }),
      sym('ar', 'obc-ar', 'poi-object-aton', 'POI Object ATON', 'Oa', { width: 48, height: 48 }),
      sym('ar', 'obc-ar', 'poi-object-data', 'POI Object Data', 'Od', { width: 48, height: 48 }),
      sym('ar', 'obc-ar', 'chart-object-vessel-button', 'Chart Vessel Button', 'Cv', { width: 48, height: 48 }),
    ],
  },
  {
    id: 'obc-building-blocks',
    name: 'Building Blocks',
    icon: '🧱',
    symbols: [
      sym('bb', 'obc-building-blocks', 'alert-list', 'Alert List', 'Al', { width: 320, height: 240 }, ['source']),
      sym('bb', 'obc-building-blocks', 'bar-vertical', 'Bar Vertical (BB)', '▮', { width: 80, height: 200 }, ['value'], { hasAlarmLimits: true }),
      sym('bb', 'obc-building-blocks', 'bar-horizontal', 'Bar Horizontal (BB)', '▬', { width: 200, height: 80 }, ['value'], { hasAlarmLimits: true }),
      sym('bb', 'obc-building-blocks', 'circular-progress', 'Circular Progress (BB)', '◔', { width: 80, height: 80 }, ['value']),
      sym('bb', 'obc-building-blocks', 'instrument-radial', 'Instrument Radial (BB)', '◉', { width: 160, height: 160 }, ['value'], { hasAlarmLimits: true }),
    ],
  },
];

export const OBC_CATALOG_SYMBOL_TYPES = new Set(
  OPENBRIDGE_CATALOG_LIBRARY.flatMap(cat => cat.symbols.map(s => s.type))
);
